/**
 * Slack Service Module
 * Handles sending meal plans to Slack via webhook
 */

require('dotenv').config();
const axios = require('axios');

// ============================================
// CONFIGURATION
// ============================================

const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL;
const TIMEOUT = 5000; // 5 seconds
const MAX_RETRIES = 1; // Single retry as per PRD

// Validate webhook URL (warn but don't fail - Slack is optional)
if (!SLACK_WEBHOOK_URL) {
  console.warn('⚠️ SLACK_WEBHOOK_URL not configured. Slack integration will be disabled.');
}

// ============================================
// MAIN FUNCTIONS
// ============================================

/**
 * Send meal plan to Slack
 * @param {Object} mealPlan - Meal plan with meals array
 * @returns {Promise<Object>} Status object with success and message
 */
async function sendToSlack(mealPlan) {
  // Check if webhook is configured
  if (!SLACK_WEBHOOK_URL) {
    console.warn('⚠️ Slack webhook not configured, skipping Slack send');
    return {
      success: false,
      message: 'Slack integration is not configured',
    };
  }
  
  if (!mealPlan || !mealPlan.meals || mealPlan.meals.length === 0) {
    console.error('❌ Invalid meal plan provided to Slack service');
    return {
      success: false,
      message: 'Invalid meal plan data',
    };
  }
  
  console.log('📤 Sending meal plan to Slack...', {
    meals: mealPlan.meals.length,
    timestamp: new Date().toISOString(),
  });
  
  // Format message
  const slackMessage = formatMealPlanMessage(mealPlan);
  
  // Send with retry logic
  try {
    await sendWithRetry(slackMessage);
    
    console.log('✅ Meal plan sent to Slack successfully');
    
    return {
      success: true,
      message: 'Meal plan sent to Slack successfully',
    };
  } catch (error) {
    console.error('❌ Failed to send to Slack:', error.message);
    
    return {
      success: false,
      message: 'Failed to send to Slack. Please try again.',
    };
  }
}

/**
 * Format meal plan as Slack message with blocks
 * @param {Object} mealPlan - Meal plan with meals array
 * @returns {Object} Slack message object
 */
function formatMealPlanMessage(mealPlan) {
  // Format meals as markdown text
  const mealsText = mealPlan.meals
    .map(meal => {
      return `*${meal.day}:* ${meal.title}\n${meal.description}\n⏱️ ${meal.cookingTime} | 🍴 ${meal.cuisine}`;
    })
    .join('\n\n');
  
  // Create Slack message with blocks
  const message = {
    text: '🍽️ Weekly Meal Plan Generated!',
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '🍽️ This Week\'s Meal Plan',
          emoji: true,
        },
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: mealsText,
        },
      },
      {
        type: 'divider',
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `Generated by Geeta's AI Meal Planner | ${new Date().toLocaleDateString('en-US', { 
              weekday: 'long', 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}`,
          },
        ],
      },
    ],
  };
  
  return message;
}

/**
 * Send message to Slack webhook with retry
 * @param {Object} message - Slack message object
 * @returns {Promise<void>}
 */
async function sendWithRetry(message) {
  let lastError;
  
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const response = await axios.post(SLACK_WEBHOOK_URL, message, {
        timeout: TIMEOUT,
        headers: {
          'Content-Type': 'application/json',
        },
      });
      
      if (response.status === 200) {
        return; // Success
      }
      
      throw new Error(`Unexpected status code: ${response.status}`);
      
    } catch (error) {
      lastError = error;
      
      if (attempt < MAX_RETRIES) {
        console.warn(`⚠️ Slack send attempt ${attempt + 1} failed, retrying...`);
        await new Promise(resolve => setTimeout(resolve, 1000)); // 1 second delay
      }
    }
  }
  
  // All retries exhausted
  throw lastError;
}

// ============================================
// EXPORTS
// ============================================

module.exports = {
  sendToSlack,
};
